#!/bin/sh
#
#  DEFAULT TRINITY STARTUP SCRIPT
#

# This block may not be appropriate for all systems.
# It should work for command line logins but graphical
# login managers may source these files already.
# Multiple sourcing is not a problem when the files are only
# containers for environment variables and such.
if [ -r /etc/xprofile ]; then
  source /etc/xprofile
fi
if [ -r $HOME/.xprofile ]; then
  source $HOME/.xprofile
fi

echo "[starttde] Starting starttde." 1>&2
echo "[starttde] This script is $0" 1>&2

# Avoid any possible conflict with KDE4. Therefore within this script
# use full path names to all binaries used.

# The binaries for TDE are located in the same place as this script.
# To determine that location use the following method rather than presuming
# the existence of $TDEDIR. That environment variable might not be
# defined or defined to point to KDE4 binaries.
BIN_DIR="`dirname \`readlink -f $0\``"
# Do not use tde-config to determine the version. That command creates a
# profile directory in the root of the file system. Refer to Bug Report 293.
if [ -x $BIN_DIR/konqueror ]; then
  TDE_VERSION="`$BIN_DIR/konqueror --version | grep TDE | awk '{print $2}'`"
  echo "[starttde] TDE version is $TDE_VERSION" 1>&2
  TDEDIR=`echo $BIN_DIR | sed 's|/bin||'`
  echo "[starttde] TDE base directory is $TDEDIR" 1>&2
  echo
else
  echo "[starttde] Unable to determine TDE base directory."
  echo "[starttde] This script should be installed in the same directory."
  echo "[starttde] Exiting."
  exit 1
fi
unset BIN_DIR

# When the X server dies we get a HUP signal from xinit. We must ignore it
# because we still need to do some cleanup.
trap '[starttde] echo GOT SIGHUP' HUP

# Check if a TDE session is already running.
if kcheckrunning >/dev/null 2>&1; then
  echo "[starttde] TDE seems to be already running on this display."
  xmessage -center -geometry 500x100 "TDE seems to be already running on this display." > /dev/null 2>/dev/null
  exit 1
fi

# Set the background color.
# The standard X background is nasty, causing moire effects and exploding
# people's heads. We use colours from the standard TDE palette for those with
# palettised displays.
if test -z "$XDM_MANAGED" || echo "$XDM_MANAGED" | grep ",auto" > /dev/null; then
  xsetroot -solid "#618DCC" # sky blue
fi

# Unset this for Darwin since it will screw up TDE's dynamic-loading
unset DYLD_FORCE_FLAT_NAMESPACE

# Check whether prelinking is enabled. If so, exporting TDE_IS_PRELINKED improves
# loading TDE. The $TDE_IS_PRELINKED variable might already be set on some systems
# through /etc/profile.d, so first check whether the variable exists.
if [ -z $TDE_IS_PRELINKED ]; then
  if [ -r /etc/default/prelink ]; then
    . /etc/default/prelink
    if [ "$PRELINKING" == "yes" ]; then
      export TDE_IS_PRELINKED=1
    fi
  fi
fi

# In case we have been started with full pathname spec without being in PATH.
bindir=`readlink -f "$0" | sed -n 's,^\(/.*\)/[^/][^/]*$,\1,p'`
if [ -n "$bindir" ]; then
  case $PATH in
    $bindir|$bindir:*|*:$bindir|*:$bindir:*) ;;
    *) PATH=$bindir:$PATH; export PATH;;
  esac
fi

# Boot sequence:
#
# tdeinit is used to fork off processes which improves memory usage
# and startup time.
#
# * tdeinit starts the dcopserver and klauncher first.
# * Then kded is started. kded is responsible for keeping the sycoca
#   database up to date. When an up to date database is present it goes
#   into the background and the startup continues.
# * Then tdeinit starts kcminit. kcminit performs initialisation of
#   certain devices according to the user's settings
#
# * Then ksmserver is started which takes control of the rest of the startup sequence

# The user's personal TDE directory usually is $HOME/.trinity.
# This setting may be overridden by setting $TDEHOME. When migrating profiles
# must be careful here because $HOME/.kde was used commonly in the pre-KDE4
# days for the user's TDE profile, but now with KDE4 common on systems,
# $HOME/.kde might point to KDE4 profile settings. The existence of KDE4
# does not mean all people are using KDE4.

if [ -n "$TDEHOME" ]; then
  echo "[starttde] TDEHOME is preset to $TDEHOME." 1>&2
  export TDEHOME=$TDEHOME
else
  # $TDEHOME is NOT already preset in the environment. Try to help.
  # This might be overkill but does provide flexibility.
  # This script and kstandardirs.h and kstandardirs.cpp must match.
  # The latter two must be edited/patched before compiling.
  echo "[starttde] TDEHOME is not set." 1>&2
  if [ -d $HOME/.trinity ]; then
    # OK, this one is obvious.
    export TDEHOME=$HOME/.trinity
  elif [ -f /usr/bin/kde4-config ]; then
    # Looks like KDE4 is installed.
    if [ -d $HOME/.kde ] && [ ! -d $HOME/.trinity ]; then
      # Presume $HOME/.kde is being used for KDE4 as it already exists.
      export TDEHOME=$HOME/.trinity
    else
      # Presume $HOME/.kde is being used for KDE4 to be on the safe side.
      export TDEHOME=$HOME/.trinity
    fi
  elif [ -f /opt/trinity/bin/tde-config ]; then
    # Looks like Trinity is installed.
    export TDEHOME=$HOME/.trinity
  elif [ -f /usr/bin/tde-config ] && [ -d $HOME/.kde ]; then
    # Looks like Trinity is installed and not playing second fiddle to KDE4.
    export TDEHOME=$HOME/.kde
  else
    # Resort to this and hope for the best!
    export TDEHOME=$HOME/.trinity
  fi
  echo "[starttde] Set TDEHOME to $TDEHOME." 1>&2
fi

# Do we want to run this script from here in such an automated manner?
# Or leave the script to be run only at the user's discretion?
# The migratekde3 script as written (in draft) requires user intervention,
# which to succeed in TDE needs something like KDialog. Refer to the
# commentary in migratekde3 for more details.
# if [ -x $TDEDIR/migratekde3 ]; then
#   sh $TDEDIR/migratekde3
# fi

# kdesu needs something to find root's TDE profile. Set the TDEROOTHOME variable
# here as last resort. /root/.trinity is a safe presumption. If an admin wants
# a different location then set the TDEROOTHOME variable elsewhere.
if [ -z "$TDEROOTHOME" ]; then
  export TDEROOTHOME=/root/.trinity
  echo "[starttde] Setting TDEROOTHOME to $TDEROOTHOME."
fi

# Modify the following environment variables only as necessary.
if [ -d $TDEDIR/games ]; then
  if [ -z "`echo $PATH | grep \"$TDEDIR/games\"`" ]; then
    export PATH=$TDEDIR/games:$PATH
  fi
fi
if [ -d $TDEDIR/bin ]; then
  if [ -z "`echo $PATH | grep \"$TDEDIR/bin\"`" ]; then
    export PATH=$TDEDIR/bin:$PATH
  fi
fi
if [ -d $TDEDIR/share ]; then
  if [ -z "`echo $XDG_DATA_DIRS | grep \"$TDEDIR/share\"`" ]; then
    if [ "$XDG_DATA_DIRS" = "" ]; then
      XDG_DATA_DIRS=$TDEDIR/share
    else
      XDG_DATA_DIRS=$XDG_DATA_DIRS:$TDEDIR/share
    fi
    export XDG_DATA_DIRS
  fi
fi
if [ -d $TDEDIR/etc/xdg ]; then
  if [ -z "`echo $XDG_CONFIG_DIRS | grep \"$TDEDIR/etc/xdg\"`" ]; then
    if [ "$XDG_CONFIG_DIRS" = "" ]; then
      XDG_CONFIG_DIRS=$TDEDIR/etc/xdg
    else
      XDG_CONFIG_DIRS=$XDG_CONFIG_DIRS:$TDEDIR/etc/xdg
    fi
    export XDG_CONFIG_DIRS
  fi
fi
if [ -d $TDEDIR/share/man ]; then
  if [ -z "`echo $MANPATH | grep \"$TDEDIR/share/man\"`" ]; then
    export MANPATH=$TDEDIR/share/man:$MANPATH
  fi
fi

test -n "$TDEHOME" && tdehome=`echo "$TDEHOME" | sed "s,^~/,$HOME/,"`

# Allow interested applications, such as the Plasma control wrapper,
# to know that this is a Trinity desktop and not a TDE one.
export DESKTOP_SESSION=trinity

# Please see kstartupconfig source for usage.
if [ ! -d "$HOME/.trinity" ]; then
  echo "[starttde] Creating $HOME/.trinity." 1>&2
fi
mkdir -m 700 -p $tdehome
mkdir -m 700 -p $tdehome/share
mkdir -m 700 -p $tdehome/share/config
cat >$tdehome/share/config/startupconfigkeys <<EOF
kcminputrc Mouse cursorTheme ''
kcminputrc Mouse cursorSize ''
kpersonalizerrc General FirstLogin true
ksplashrc KSplash Theme Default
kcmrandrrc Display ApplyOnStartup false
kcmrandrrc [Screen0]
kcmrandrrc [Screen1]
kcmrandrrc [Screen2]
kcmrandrrc [Screen3]
kcmfonts General forceFontDPI 0
EOF
$TDEDIR/bin/kstartupconfig
if test $? -ne 0; then
  xmessage -center -geometry 500x100 "Could not start kstartupconfig. Check your installation."
fi
# $tdehome/share/config/startupconfig should exist but avoid script failure if not.
if [ -r $tdehome/share/config/startupconfig ]; then
  . $tdehome/share/config/startupconfig
fi

# Make sure a default wallpaper is set.
if [ ! -e $tdehome/share/config/kdesktoprc ]; then
 # With Trinity this file should exist, but test first.
  if [ -r /usr/share/wallpapers/isadora.png.desktop ]; then
cat >$tdehome/share/config/kdesktoprc <<EOF
[Desktop0]
Wallpaper=isadora.png
WallpaperMode=Scaled
EOF
  fi
fi

# XCursor mouse theme needs to be applied here to work even for kded or ksmserver.
if test -n "$kcminputrc_mouse_cursortheme" -o -n "$kcminputrc_mouse_cursorsize" ; then
  kapplymousetheme "$kcminputrc_mouse_cursortheme" "$kcminputrc_mouse_cursorsize"
  if test $? -eq 10; then
    export XCURSOR_THEME=default
  elif test -n "$kcminputrc_mouse_cursortheme"; then
    export XCURSOR_THEME="$kcminputrc_mouse_cursortheme"
  fi
  if test -n "$kcminputrc_mouse_cursorsize"; then
    export XCURSOR_SIZE="$kcminputrc_mouse_cursorsize"
  fi
fi

if test "$kcmrandrrc_display_applyonstartup" = "true"; then
  # 4 screens is hopefully enough
  for scrn in 0 1 2 3; do
    args=
    width="\$kcmrandrrc_screen${scrn}_width" ; eval "width=$width"
    height="\$kcmrandrrc_screen${scrn}_height" ; eval "height=$height"
    if test -n "${width}" -a -n "${height}"; then
      args="$args -s ${width}x${height}"
    fi
    refresh="\$kcmrandrrc_screen${scrn}_refresh" ; eval "refresh=$refresh"
    if test -n "${refresh}"; then
      args="$args -r ${refresh}"
    fi
    rotation="\$kcmrandrrc_screen${scrn}_rotation" ; eval "rotation=$rotation"
    if test -n "${rotation}"; then
      case "${rotation}" in
        0)
          args="$args -o 0"
          ;;
        90)
          args="$args -o 1"
          ;;
        180)
          args="$args -o 2"
          ;;
        270)
          args="$args -o 3"
          ;;
      esac
    fi
    reflectx="\$kcmrandrrc_screen${scrn}_reflectx" ; eval "reflectx=$reflectx"
    if test "${refrectx}" = "true"; then
      args="$args -x"
    fi
    reflecty="\$kcmrandrrc_screen${scrn}_reflecty" ; eval "reflecty=$reflecty"
    if test "${refrecty}" = "true"; then
      args="$args -y"
    fi
    if test -n "$args"; then
      xrandr $args
    fi
  done
fi

dl=$DESKTOP_LOCKED
unset DESKTOP_LOCKED # Don't want it in the environment

# Launch splash that doesn't need any TDE libraries here, before
# TDE libraries are loaded into memory (which may take some time
# with cold caches). Makes the splash appear sooner.
# If kpersonalizer needs to be run splash will be started only later.
if test -z "$dl" && test "$kpersonalizerrc_general_firstlogin" != "true"; then
  case "$ksplashrc_ksplash_theme" in
    Simple)
      ksplashsimple
      ;;
    *)
      ;;
  esac
fi

if test "$kcmfonts_general_forcefontdpi" -eq 120; then
  xrdb -quiet -merge -nocpp <<EOF
Xft.dpi: 120
EOF
elif test "$kcmfonts_general_forcefontdpi" -eq 96; then
  xrdb -quiet -merge -nocpp <<EOF
Xft.dpi: 96
EOF
fi

# Configuration of the gtk_qt_engine if not already set.

if test -n "$TDEDIRS"; then
  tdedirs_first=`echo "$TDEDIRS" | sed -e 's/:.*//'`
  TGTK_RC_ENGINE=$tdedirs_first/share/kgtk/gtk-qt-engine.rc.sh
  TGTK_RC_TDE1=$tdedirs_first/share/kgtk/.gtkrc-2.0-kde4
  TGTK_RC_TDE2=$tdedirs_first/share/kgtk/.gtkrc-2.0-kde-kde4
else
  TGTK_RC_ENGINE=$TDEDIR/share/kgtk/gtk-qt-engine.rc.sh
  TGTK_RC_TDE1=$TDEDIR/share/kgtk/.gtkrc-2.0-kde4
  TGTK_RC_TDE2=$TDEDIR/share/kgtk/.gtkrc-2.0-kde-kde4
fi

if [ ! -e $tdehome/env/gtk-qt-engine.rc.sh ] && [ -e $TGTK_RC_ENGINE ]
then
 mkdir -p $tdehome/env
 cp -f $TGTK_RC_ENGINE $tdehome/env
 chmod 755 $tdehome/env/gtk-qt-engine.rc.sh
fi

if [ ! -e $HOME/.gtkrc-2.0-kde4 ] && [ -e $TGTK_RC_TDE1 ]
then
 cp -f $TGTK_RC_TDE1 $HOME
fi

if [ ! -e $HOME/.gtkrc-2.0-kde-kde4 ] && [ -e $TGTK_RC_TDE2 ]
then
 cp -f $TGTK_RC_TDE2 $HOME
fi

# Source scripts found in <localprefix>/env/*.sh and <prefixes>/env/*.sh
# (where <localprefix> is $TDEHOME or ~/.trinity, and <prefixes> is where TDE is installed)
#
# This is where you can define environment variables that will be available to
# all TDE programs, so this is where you can run agents using e.g. eval `ssh-agent`
# or eval `gpg-agent --daemon`.
# Note: if you do that, you should also put "ssh-agent -k" as a shutdown script
#
# (see end of this file).
# For anything else (that doesn't set env vars, or that needs a window manager),
# better use the Autostart folder.

exepath=`tde-config --path exe | tr : '\n'`

for prefix in `echo "$exepath" | sed -n -e 's,/bin[^/]*/,/env/,p'`; do
  for file in "$prefix"*.sh; do
    test -r "$file" && . "$file"
  done
done

# Activate the TDE font directories.
#
# There are 4 directories that may be used for supplying fonts for TDE.
#
# There are two system directories. These belong to the administrator.
# There are two user directories, where the user may add her own fonts.
#
# The 'override' versions are for fonts that should come first in the list,
# i.e. if you have a font in your 'override' directory, it will be used in
# preference to any other.
#
# The preference order looks like this:
# user override, system override, X, user, system
#
# Where X is the original font database that was set up before this script
# runs.

usr_odir=$HOME/.fonts/kde-override
usr_fdir=$HOME/.fonts

# Add any user-installed font directories to the X font path
tde_fontpaths=$usr_fdir/fontpaths
do_usr_fdir=1
do_usr_odir=1
if test -r "$tde_fontpaths" ; then
  savifs=$IFS
  IFS="
"
  for fpath in `grep -v '^[   ]*#' < "$tde_fontpaths"` ; do
    rfpath=`echo $fpath | sed "s:^~:$HOME:g"`
    if test -s "$rfpath"/fonts.dir; then
      xset fp+ "$rfpath"
      if test "$rfpath" = "$usr_fdir"; then
        do_usr_fdir=0
      fi
      if test "$rfpath" = "$usr_odir"; then
        do_usr_odir=0
      fi
    fi
  done
  IFS=$savifs
fi

if [ ! -n "$TDEDIR" ]; then
  export TDEDIR=`echo "$TDEDIRS" | sed -e 's/:.*//'`
fi

echo "[starttde] TDEDIR: $TDEDIR" 1>&2
echo "[starttde] TDEDIRS: $TDEDIRS" 1>&2

if test -n "$TDEDIRS"; then
  tdedirs_first=`echo "$TDEDIRS" | sed -e 's/:.*//'`
  sys_odir=$tdedirs_first/share/fonts/override
  sys_fdir=$tdedirs_first/share/fonts
else
  sys_odir=$TDEDIR/share/fonts/override
  sys_fdir=$TDEDIR/share/fonts
fi

if test -n "$TDEDIRS"; then
  tdedirs_first=`echo "$TDEDIRS" | sed -e 's/:.*//'`
  echo "[starttde] tdedirs_first: $tdedirs_first"
  if [ -r $tdedirs_first/share/kgtk/preload ]; then
    echo "[starttde] Reading from $tdedirs_first/share/kgtk/preload"
    read -r TGTK_PRELOAD < $tdedirs_first/share/kgtk/preload
  fi
else
  if [ -r $TDEDIR/share/kgtk/preload ]; then
    read -r TGTK_PRELOAD < $TDEDIR/share/kgtk/preload
  fi
fi

if [ -n $TGTK_PRELOAD ]; then
  if [ -e /usr/lib/libnspr4.so ]; then
    KGTK_NSPR_PRELOAD="/usr/lib/libnspr4.so:"
  fi
  export LD_PRELOAD=$TGTK_PRELOAD:$KGTK_NSPR_PRELOAD$LD_PRELOAD
fi

# We run mkfontdir on the user's font dirs (if we have permission) to pick
# up any new fonts they may have installed. If mkfontdir fails, we still
# add the user's dirs to the font path, as they might simply have been made
# read-only by the administrator, for whatever reason.

# Only do usr_fdir and usr_odir if they are *not* listed in fontpaths
if [ -e $sys_odir/fonts.dir ]
then
  xset +fp "$sys_odir"
fi
test $do_usr_odir -eq 1 && test -d "$usr_odir" && (mkfontdir "$usr_odir" ; xset +fp "$usr_odir")
test $do_usr_fdir -eq 1 && test -d "$usr_fdir" && (mkfontdir "$usr_fdir" ; xset fp+ "$usr_fdir")
test -d "$sys_fdir" && xset fp+ "$sys_fdir"

# Ask X11 to rebuild its font list.
xset fp rehash

# Set a left cursor instead of the standard X11 "X" cursor, since I've heard
# from some users that they're confused and don't know what to do. This is
# especially necessary on slow machines, where starting TDE takes one or two
# minutes until anything appears on the screen.
#
# If the user has overwritten fonts, the cursor font may be different now
# so don't move this up.
#
xsetroot -cursor_name left_ptr

# Get Ghostscript to look into user's TDE fonts dir for additional Fontmap
if test -n "$GS_LIB" ; then
  GS_LIB=$usr_fdir:$GS_LIB
  export GS_LIB
else
  GS_LIB=$usr_fdir
  export GS_LIB
fi

# Link "tmp" "socket" and "cache" resources to directory in $TMP
# Creates:
# - a directory $TMP/tde-$USER and is linked from $TDEHOME/tmp-$HOSTNAME to it.
# - a directory $TMP/tdesocket-$USER and is linked from $TDEHOME/socket-$HOSTNAME to it.
# - a directory /var/tmp/tdecache-$USER and is linked from $TDEHOME/cache-$HOSTNAME to it.
# Note: temporary locations can be overridden through the TDETMP and TDEVARTMP
# environment variables.
for resource in tmp cache socket; do
  if ! lnusertemp $resource >/dev/null; then
    echo "[starttde] Call to lnusertemp failed (temporary directories full?). Check your installation." 1>&2
    xmessage -center -geometry 600x100 "Call to lnusertemp failed (temporary directories full?). Check your installation."
    exit 1
  fi
done

# In case of dcop sockets left by a previous session, cleanup.
$TDEDIR/bin/dcopserver_shutdown

echo '[starttde] Starting Trinity...'  1>&2

# Detect any running Xorg composition managers
$TDEDIR/bin/kdetcompmgr

# Run KPersonalizer before the session if this is the first login.
if test "$kpersonalizerrc_general_firstlogin" = "true"; then
  if [ ! -x $TDEDIR/bin/kpersonalizer ]; then
    echo "[starttde] kpersonalizer not found! Please install in order to properly configure your user profile." 1>&2
  else
    # start only dcopserver, don't start whole tdeinit (takes too long)
    echo "[starttde] Running kpersonalizer..." 1>&2
    $TDEDIR/bin/dcopserver
    $TDEDIR/bin/twin --lock &
    $TDEDIR/bin/kpersonalizer --before-session
    # handle kpersonalizer restarts (language change)
    while test $? -eq 1; do
      $TDEDIR/bin/kpersonalizer --r --before-session
    done
    $TDEDIR/bin/dcopquit twin
    $TDEDIR/bin/dcopserver_shutdown --wait
  fi
fi

# Remove moodin cache if we have a new wallpaper installed, jriddell. Distro-specific.
if [ -d $tdehome/share/apps/ksplash/cache/Moodin/kubuntu ]; then
  if [ /usr/share/wallpapers/kubuntu-wallpaper.png -nt $tdehome/share/apps/ksplash/cache/Moodin/kubuntu/ ]; then
    rm -rf $tdehome/share/apps/ksplash/cache/Moodin/kubuntu/
  fi
fi

if test -z "$dl"; then
  # the splashscreen and progress indicator
  case "$ksplashrc_ksplash_theme" in
    None)
      ;; # nothing
    Simple)
      if test "$kpersonalizerrc_general_firstlogin" = "true"; then
        $TDEDIR/bin/ksplashsimple
      fi # otherwise started earlier
      ;;
    *)
      $TDEDIR/bin/ksplash --nodcop
      ;;
  esac
fi

# Mark that full TDE session is running (e.g. Konqueror preloading works only
# with full TDE running). The TDE_FULL_SESSION property can be detected by
# any X client connected to the same X session, even if not launched
# directly from the TDE session but e.g. using "ssh -X", kdesu. $TDE_FULL_SESSION
# however guarantees that the application is launched in the same environment
# like the TDE session and that e.g. TDE utilities/libraries are available.
# The matching tests are:
#   For $TDE_FULL_SESSION:
#     if test -n "$TDE_FULL_SESSION"; then ... whatever
#   For TDE_FULL_SESSION property:
#     xprop -root | grep "^TDE_FULL_SESSION" >/dev/null 2>/dev/null
#     if test $? -eq 0; then ... whatever
#
# Additionally there is $TDE_SESSION_UID with the uid of the user
# running the TDE session. It should be rarely needed (for example,
# after sudo to prevent desktop-wide functionality in the new user's kded).
#
TDE_FULL_SESSION=true
export TDE_FULL_SESSION
xprop -root -f TDE_FULL_SESSION 8t -set TDE_FULL_SESSION true
echo "[starttde] TDE_FULL_SESSION: $TDE_FULL_SESSION" 1>&2
TDE_SESSION_UID=$UID
export TDE_SESSION_UID
echo "[starttde] TDE_SESSION_UID: $TDE_SESSION_UID" 1>&2

# We set LD_BIND_NOW to increase the efficiency of tdeinit.
# tdeinit unsets this variable before loading applications.
LD_BIND_NOW=true $TDEDIR/bin/start_tdeinit_wrapper --new-startup +kcminit_startup
if test $? -ne 0; then
  # Startup error
  echo '[starttde] Could not start tdeinit. Check your installation.' 1>&2
  xmessage -center -geometry 500x100 "Could not start tdeinit. Check your installation."
fi
echo "[starttde] tdeinit started successfully." 1>&2

# If the session should be locked from the start (locked autologin),
# lock now and do the rest of the TDE startup underneath the locker.
# FIXME
# kdesktop needs to be notified of this locker process somehow so that
# it does not attempt to launch its own locker process on startup!
if test -n "$dl"; then
  $TDEDIR/bin/kwrapper kdesktop_lock --forcelock &
  # Give it some time for starting up. This is somewhat unclean; some
  # notification would be better.
  sleep 1
fi

# Finally, give the session control to the session manager.
# See tdebase/ksmserver for the description of the rest of the startup sequence.
# If the TDEWM environment variable has been set, then it will be used as Trinity's
# window manager instead of twin.
# If TDEWM is not set, ksmserver will ensure twin is started.
# kwrapper is used to reduce startup time and memory usage
# kwrapper does not return usefull error codes such as the exit code of ksmserver.
# We only check for 255 which means that the ksmserver process could not be
# started, any problems thereafter, e.g. ksmserver failing to initialize,
# will remain undetected.
$TDEDIR/bin/tdeinit_phase1
if test $? -eq 255; then
  # Startup error
  echo '[starttde] An error was detected while attempting to load the session manager via tdeinit_phase1. Please check your installation for problems.' 1>&2
  xmessage -center -geometry 500x100 "An error was detected while attempting to load the session manager via tdeinit_phase1. Please check your installation for problems."
fi

# wait if there's any crashhandler shown
while $TDEDIR/bin/dcop | grep -q ^drkonqi- ; do
  sleep 5
done

echo '[starttde] Shutting down Trinity...'  1>&2

# Clean up
$TDEDIR/bin/tdeinit_shutdown
$TDEDIR/bin/dcopserver_shutdown --wait
$TDEDIR/bin/artsshell -q terminate
# KDE4 support
if [ -f /usr/bin/kdeinit4_shutdown ]; then
  /usr/bin/kde4 kdeinit4_shutdown 2>/dev/null
fi

echo '[starttde] Running Trinity shutdown scripts...'  1>&2

# Run scripts found in $TDEDIRS/shutdown
for prefix in `echo "$exepath" | sed -n -e 's,/bin[^/]*/,/shutdown/,p'`; do
  for file in `ls "$prefix" 2> /dev/null | egrep -v '(~|\.bak)$'`; do
    if [ -x "${prefix}${file}" ]; then
      echo "[starttde] Running ${prefix}${file}." 1>&2
      sh ${prefix}${file}
    fi
  done
done

unset TDE_FULL_SESSION
xprop -root -remove TDE_FULL_SESSION
unset TDE_SESSION_UID

# Initialize_Status_Header
echo "[starttde] Trinity shutdown complete." 1>&2
