[Desktop Entry]
Exec=@TDE_BIN_DIR@/kdesktop
X-DCOP-ServiceType=wait
Name=TDE Desktop
Name[af]=TDE Werkskerm
Name[ar]=سطح المكتب TDE
Name[az]=TDE Masa üstü
Name[be]=Працоўны стол TDE
Name[bn]=কে.ডি.ই. ডেস্কটপ
Name[br]=Burev TDE
Name[bs]=TDE radna površina
Name[ca]=Escriptori TDE
Name[cs]=Pracovní plocha TDE
Name[csb]=Pùlt TDE
Name[cy]=Penbwrdd TDE
Name[da]=TDE-desktop
Name[de]=TDE-Arbeitsfläche
Name[el]=Επιφάνεια εργασίας του TDE
Name[eo]=TDE Labortablo
Name[es]=Escritorio de TDE
Name[et]=TDE töölaud
Name[eu]=TDE mahaigaina
Name[fa]=رومیزی TDE
Name[fi]=TDE-työpöytä
Name[fr]=Bureau de TDE
Name[fy]=TDE Buroblêd
Name[ga]=Deasc TDE
Name[gl]=Escritório de TDE
Name[he]=שולחן העבודה של TDE
Name[hi]=केडीई डेस्कटॉप
Name[hr]=TDE radna površina
Name[hu]=Munkaasztal
Name[id]=Desktop TDE
Name[is]=TDE skjáborð
Name[it]=Desktop TDE
Name[ja]=TDE デスクトップ
Name[ka]=TDE სამუშაო დაფა
Name[kk]=TDE үстелі
Name[km]=ផ្ទៃតុ TDE
Name[ko]=데스크톱
Name[lo]=ພື້ນທີ່ທຳງານ TDE
Name[lt]=TDE Darbastalis
Name[lv]=TDE Darbvirsma
Name[mk]=TDE Десктоп
Name[mn]=TДЭ-Ажлын тавцан
Name[ms]=Desktop TDE
Name[mt]=Desktop TDE
Name[nb]=TDE Skrivebord
Name[nds]=TDE-Schriefdisch
Name[ne]=TDE डेस्कटप
Name[nl]=TDE Bureaublad
Name[nn]=TDE-skrivebord
Name[nso]=Desktop ya TDE
Name[pa]=TDE ਵੇਹੜਾ
Name[pl]=Pulpit TDE
Name[pt]=Ecrã do TDE
Name[pt_BR]=Área de Trabalho TDE
Name[ro]=Ecran TDE
Name[ru]=Рабочий стол TDE
Name[rw]=TDE Ibiro 
Name[se]=TDE-čallinbeavdi
Name[sk]=Pracovná plocha
Name[sl]=Namizje TDE
Name[sr]=TDE радна површина
Name[sr@Latn]=TDE radna površina
Name[sv]=TDE-skrivbord
Name[ta]=TDE மேல்மேசை
Name[te]=కెడిఈ రంగస్థలం
Name[tg]=Мизи Кории TDE
Name[th]=พื้นที่ทำงาน TDE
Name[tr]=TDE Masaüstü
Name[tt]=TDE Östäl
Name[uk]=Стільниця TDE
Name[uz]=TDE ish stoli
Name[uz@cyrillic]=TDE иш столи
Name[ven]=Desikithopo ya TDE
Name[vi]=Môi trường TDE
Name[wa]=Sicribanne TDE
Name[zh_CN]=TDE 桌面
Name[zh_TW]=TDE 桌面
Name[zu]=I-Desktop ye-TDE
Type=Service
X-TDE-StartupNotify=false
OnlyShowIn=TDE;
X-TDE-autostart-phase=0
